import { recipeCardDto } from '../dtos/recipe-card-dto';
import { Difficulty } from '../enums/Difficulty';

export const RECIPE_CARDS: recipeCardDto[] = [
  {
    id: crypto.randomUUID(),
    name: 'Spaghetti Carbonara',
    cuisine: 'Italian',
    totalTime: 25,
    difficulty: Difficulty.Medium,
    imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0',
    rating: 4.6,
    ratingCount: 130,
  },
  {
    id: crypto.randomUUID(),
    name: 'Chicken Shawarma',
    cuisine: 'Middle Eastern',
    totalTime: 40,
    difficulty: Difficulty.Medium,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-3c379cfcc1cb',
    rating: 4.8,
    ratingCount: 230,
  },
  {
    id: crypto.randomUUID(),
    name: 'Sushi Rolls',
    cuisine: 'Japanese',
    totalTime: 60,
    difficulty: Difficulty.Hard,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c',
    rating: 4.7,
    ratingCount: 10,
  },
  {
    id: crypto.randomUUID(),
    name: 'Greek Salad',
    cuisine: 'Greek',
    totalTime: 15,
    difficulty: Difficulty.Easy,
    imageUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994',
    rating: 4.3,
    ratingCount: 23,
  },
  {
    id: crypto.randomUUID(),
    name: 'Beef Tacos',
    cuisine: 'Mexican',
    totalTime: 30,
    difficulty: Difficulty.Easy,
    imageUrl: 'https://images.unsplash.com/photo-1601924582971-c9e0e1f2a9e3',
    rating: 4.5,
    ratingCount: 28,
  },
  {
    id: crypto.randomUUID(),
    name: 'Pad Thai',
    cuisine: 'Thai',
    totalTime: 35,
    difficulty: Difficulty.Medium,
    imageUrl: 'https://images.unsplash.com/photo-1625943553855-7d68a02a22e8',
    rating: 4.9,
    ratingCount: 19,
  },
  {
    id: crypto.randomUUID(),
    name: 'Butter Chicken',
    cuisine: 'Indian',
    totalTime: 50,
    difficulty: Difficulty.Medium,
    imageUrl: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f',
    rating: 4.8,
    ratingCount: 64,
  },
  {
    id: crypto.randomUUID(),
    name: 'Cheeseburger',
    cuisine: 'American',
    totalTime: 20,
    difficulty: Difficulty.Easy,
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349',
    rating: 4.2,
    ratingCount: 53,
  },
];
